### ISSUE TITLE
ソードワールドシリーズのレーティング処理時の修正適用時に1ゾロでもダイス目修正を行ってしまう

### ISSUE THREAD

**Issue by raa0121** [bcdice/BCDice#106]
## 報告

```
imgsurvivor今日 19:29
こんばんは。twitter側でも報告させていただきましたが、こちらでも改めてご報告させていただきます。
ソード・ワールド2.5の威力表ロールにおいてダイス修正値($+n)を付けてロールした際、
出目が[1,1]であっても自動的失敗扱いになりませんでした。
```

![](https://cdn.discordapp.com/attachments/597133647749054464/654287100853878794/20191211_BCDice_2.png)
![](https://cdn.discordapp.com/attachments/597133647749054464/654287132382330881/20191211_BCDice_1.png)

**Comment by raa0121** [comment]
https://github.com/bcdice/BCDice/blob/c35b69749af98b20bf369bc45019dde310ff8ce8/src/diceBot/SwordWorld2_0.rb#L40-L44
ダイス目の解釈としては、1ゾロは失敗扱いなので説明と実装にミスが有るらしい

**Comment by raa0121** [comment]
```
えおふ/saronpasu今日 21:06
2.0記載(R1 P.160 一部引用、原文ママ)

威力表での自動失敗(1ゾロ)
　威力表を振ったとき、2dの出目が1ゾロだった場合

2.5記載(R1 P.144 一部引用、原文ママ)

威力表での1ゾロ
　威力表を振ったとき、2dの出目が1ゾロだった場合
```

**Comment by ysakasin** [comment]
2.0での威力表1ゾロ(ルールブックI改訂版 p160
> 威力表での自動失敗（1ゾロ）
> 　威力表を振った時、2dの出目が1ゾロであった場合、その行動自体が自動失敗（⇒103項）であったものとして扱われます。

**Comment by ysakasin** [comment]
## 期待される挙動

### SW
N/A

### SW2.0
```
input:
K10$1
output:
SwordWorld2.0 : KeyNo.10m[1] ＞ 2D:[1,1]=3 ＞ ** ＞ 自動的失敗
rand:1/6,1/6
```

### SW2.5
```
input:
K10$1
output:
SwordWorld2.5 : KeyNo.10m[1] ＞ 2D:[1,1]=3 ＞ ** ＞ 0
rand:1/6,1/6
```
