### ISSUE TITLE
メタリックガーディアン：ダイスボット改修案

### ISSUE THREAD

**Issue by ysakasin** [bcdice/BCDice#114]
> 従来機能ではクリティカル、ファンブルの変動に対応するためには
> 2d6+m>=t[c,f]と目標値を必ず設定する必要があったが
> 目標値の存在しない判定（対決を行う場合の能動側）が存在するため
> 使いにくかった。
> 
> ここで以下の機能を実装。
> 
> MG+m[c,f]が与えられた場合、目標値なしの判定を行うことができる。
> MG=2d6であるが、この時にクリティカル値cを出目が上回った場合に自動成功、
> 
> ファンブル値fを出目が下回った場合に自動失敗を自動で検知する。
> デフォルトは従来通りc=12,f=2とする。

by @RKcolonel 

Ref. #113

**Comment by ysakasin** [comment]
@RKcolonel

`MG` を新設せずとも、 従来の記法と並行して `2d6+m[c,f]` や `2d6[c,f]` と書けるようにすれば十分使いやすくなると思いますがどうでしょうか

**Comment by RKcolonel** [comment]
@ysakasin 
ご指摘ありがとうございます。MGを新設したというよりも
元より2d6とMGが共存していたものを改造した、というのが正しいですね。
後ご指摘の2d6+m[c,f]のまま、判定が出来ればいいというのはごもっともなのですが、
システム上今度は判定ではない場合にもクリティカル、ファンブル判定を行ってしまうため、
その区別の意味合いがありました。
対策としては[c,f]を必須にするということが考えられますが、
それなら元から判定に使われていたMGを変換する方が効率的と判断させていただきました。

後添付ソースについてはudonarium移植用に作っていたものを添付していたため、Ruby側でのソースは以下になります。

  def rollDiceCommand(command)
    
    result = checkRoll(command)
    return result unless(result.empty?)
    
    debug("比較判定ロールではなかった")
    
    result = checkRoll2(command)
    return result unless(result.empty?)

    debug("判定ロールではなかった")
    debug("各種表として処理")
    return rollTableCommand(command)
  end
  
  
  def checkRoll(string)
    output = ''
    
    crit = 12
    fumble = 2
    
    return output unless(/^2D6([\+\-\d]*)>=(\d+)(\[(\d+)?(,(\d+))?\])?$/i =~ string)
    
    modText = $1
    target = $2.to_i
    crit = $4.to_i if($4)
    fumble = $6.to_i if($6)
    
    mod = 0
    mod = parren_killer("(0#{modText})") unless( modText.nil? )
    
    total, dice_str, = roll(2, 6, @sortType && 1)
    total_n = total + mod.to_i
    dum = total - total_n
    if(total_n==total)
      output = "#{total}[#{dice_str}] → #{total_n}"
    elsif(total_n>total)
      output = "#{total}[#{dice_str}]＋#{mod} → #{total_n}"
    else
      output = "#{total}[#{dice_str}]－#{dum} → #{total_n}"
    end
    
    if(total >= crit)
      output += " ＞ 自動成功"
    elsif(total <= fumble)
      output += " ＞ 自動失敗"
    elsif(total_n >= target)
      output += " ＞ 成功"
    else
      output += " ＞ 失敗"
    end
    
    output = "(#{string}) ＞ #{output}"
    
    return output
    
  end
  
  def checkRoll2(string)
    output = ''
    
    crit = 12
    fumble = 2
    
    return output unless(/^2DD6([\+\-\d]*)(\[(\d+)?(,(\d+))?\])?$/i =~ string)
    
    modText = $1
    crit = $3.to_i if($3)
    fumble = $5.to_i if($5)
    
    mod = 0
    mod = parren_killer("(0#{modText})") unless( modText.nil? )
    
    total, dice_str, = roll(2, 6, @sortType && 1)
    total_n = total + mod.to_i
    dum = total - total_n
    if(total_n==total)
      output = "#{total}[#{dice_str}] → #{total_n}"
    elsif(total_n>total)
      output = "#{total}[#{dice_str}]＋#{mod} → #{total_n}"
    else
      output = "#{total}[#{dice_str}]－#{dum} → #{total_n}"
    end
    
    if(total >= crit)
      output += " ＞ 自動成功"
    elsif(total <= fumble)
      output += " ＞ 自動失敗"
    end
    
    output = "(#{string}) ＞ #{output}"
    
    return output
    
  end

**Comment by ysakasin** [comment]
`2D6+m[c,f]` で判定できることは悪くないと思うので、以下のようにしようと思うのですがどうでしょう。

- `2D6+m`
  - クリティカル/ファンブル判定無し
- `2D6+m[c,f]`
  - クリティカル/ファンブル判定有り
- `MG+m`
  - `2D6+m[2,12]` に変換
- `MG+m[c,f]`
  - `2D6+m[c,f]` に変換

**Comment by RKcolonel** [comment]
確かにそれであれば私の実装したい形とほぼ同じになりますね。
分かりました、この形でお願いします。
ありがとうございます

**Comment by ysakasin** [comment]
https://github.com/bcdice/BCDice/pull/123 にて対応しました
