### ISSUE TITLE
新クトゥルフのボーナス・ペナルティダイスで Tens d10 を区別したい

### ISSUE THREAD

**Issue by ccfolia** [bcdice/BCDice#133]
新クトゥルフで`cc2`や`cc-2`などのダイスを振った際に、十の位のダイスが3個と1の位のダイスが1個振られる。この時`dices`の内容がd10が3回振られた扱いになるため、ツールの表示上でどれが十の位と一の位のダイスが区別できなくなってしまう。この処理自体は妥当なものだが、何かしらの手段で区別できるようになると嬉しい。

![スクリーンショット 2020-03-12 14 40 21](https://user-images.githubusercontent.com/43709944/76490936-b770ec80-646f-11ea-92f1-049d3d957ef3.png)

**As-is**
```:javascript
// result
{
  ...
  dices: [{faces: 10, value: 4}, {faces: 10, value: 2}, {faces: 10, value: 3}, {faces: 10, value: 6}]
  ...
}
```

互換性を考えるとオプションで制御できるようにすべき...？

**Comment by ysakasin** [comment]
@ccfolia 以前意見をいただいた時から考えていたのを実装してみましたので、ご意見いただけると嬉しいです。

実装: #134

**Comment by ysakasin** [comment]
先にあげた実装がmasterにマージされました。近日リリースします。
