### ISSUE TITLE
README の wiki への転載、分割

### ISSUE THREAD

**Issue by ochaochaocha3** [bcdice/BCDice#16]
現在 README.txt が約 1,800 行と非常に長く、必要な情報を探すのが大変ではないかと感じました。そこで、
1. README.txt の内容を Markdown 形式で書く。
2. このリポジトリの wiki（右部）に分割してまとめ、参照しやすくする。バージョンアップ時にリポジトリに含まれるファイルと wiki の内容をできるだけ同期させる。

ということを提案したいと思います。いかがでしょうか。

**Comment by ochaochaocha3** [comment]
途中までですが、例を作ってみました。

* [README.md](https://github.com/ochaochaocha3/BCDice/blob/4a7134a081ffa810b5922ebdaa62ff21b913771e/README.md)
    * [ボットの利用法：ダイス](https://github.com/ochaochaocha3/BCDice/blob/4a7134a081ffa810b5922ebdaa62ff21b913771e/doc/dice.md)
    * [更新履歴](https://github.com/ochaochaocha3/BCDice/blob/4a7134a081ffa810b5922ebdaa62ff21b913771e/CHANGELOG.md)
* [LICENSE](https://github.com/ochaochaocha3/BCDice/blob/4a7134a081ffa810b5922ebdaa62ff21b913771e/LICENSE.md)

**Comment by torgtaitai** [comment]
いいですね！
どどんとふ側がど＠えむで公開することも考えてあえてmdではなくhtmlにしてあるのですが、
B&C2.x は確かにmd形式にしない理由はありませんね。
サブディレクトリとしてmdディレクトリなりを置いて、そこにまとめる形が分かりやすいでしょうかね。

READMEの中身もかなり増改築で不統一なところもあると思いますので、
整理という意味でもよいと思います。是非やたいと思います。

**Comment by ochaochaocha3** [comment]
ありがとうございます！ 

作業についてもぜひ協力したいと思います。よろしくお願いします。
