### ISSUE TITLE
AddDice: 加算ロールの項なしでも実行できるようになった

### ISSUE THREAD

**Issue by ochaochaocha3** [bcdice/BCDice#170]
加算ロールの処理の変更に伴い、数字だけ、数値の四則演算だけでも実行できるようになりました。
これはこれで便利ですが（IRCボット ~「[OD TOOL for TRPG](http://odproject.net/wiki/?%C5%B7%E6%C6%A4%B1%A4%EB%A5%B4%A5%D6%A5%EA%A5%F3%C4%E2%2FTRPG%20Tools%2FOD%20TOOL%20for%20TRPG%2FReference)」~ 「[SW2\_DLL](http://w10.oroti.net/~lintmil/atriv/index.php?%BC%AB%BA%EE%A5%BD%A5%D5%A5%C8%2FSW2_DLL%20Dice%20Extender%2FReference#weeb07fb)」などで実装例あり）、意図していない動作だと思われます。
少なくとも、`C` コマンドと除算 `/` の端数処理が異なる（`C` では、ダイスボットごとに変化するが、加算ロールでは切り捨て固定）ことは、利用者側からは分かりにくい点です。

```
$ ruby cgiDiceBot.rb '42' DiceBot

DiceBot : (42) ＞ 42 ＞ 42
```

```
$ ruby cgiDiceBot.rb '1+2' DiceBot

DiceBot : (1+2) ＞ 1+2 ＞ 3
```

```
$ ruby cgiDiceBot.rb 'C(10/3)' Warhammer

Warhammer : 計算結果 ＞ 4

$ ruby cgiDiceBot.rb '10/3' Warhammer

Warhammer : (10/3) ＞ 10/3 ＞ 3
```

**Comment by ysakasin** [comment]
これは意図しない挙動ですし、混乱を招きそうなので修正します。
`C` を書かなくても数式計算ができる機能自体はあった方が便利なので、あとで検討ですかね。
