### ISSUE TITLE
Unable to join channels

### ISSUE THREAD

**Issue by wozaiha** [bcdice/BCDice#19]
> "start!"
> D, [2016-03-30T15:48:02.400845 #5836] DEBUG -- : start begin
> D, [2016-03-30T15:48:02.434478 #5836] DEBUG -- : on_connected calling..
> D, [2016-03-30T15:48:02.435473 #5836] DEBUG -- : call...
>   -> IRC server is connected.
> login to channels(#test), so wait a moment...
> D, [2016-03-30T15:48:02.436475 #5836] DEBUG -- : on_connected passed
> D, [2016-03-30T15:48:02.436475 #5836] DEBUG -- : post PASS
> D, [2016-03-30T15:48:02.436475 #5836] DEBUG -- : post NICK
> D, [2016-03-30T15:48:02.436475 #5836] DEBUG -- : SEND: NICK bcDICE
> D, [2016-03-30T15:48:02.437476 #5836] DEBUG -- : post USER
> D, [2016-03-30T15:48:02.437476 #5836] DEBUG -- : SEND: USER v2.02.29 0 \* rubydice
> D, [2016-03-30T15:48:02.437476 #5836] DEBUG -- : while loop begin
> D, [2016-03-30T15:48:02.507467 #5836] DEBUG -- : RECEIVE: :ircfire.linuxfire.com.cn NOTICE AUTH :**\* Looking up your hostname...
> D, [2016-03-30T15:48:02.507467 #5836] DEBUG -- : calling... on_xxx : on_notice
> D, [2016-03-30T15:48:02.508464 #5836] DEBUG -- : RECEIVE: :ircfire.linuxfire.com.cn NOTICE AUTH :**\* Couldn't resolve your hostname; using your IP address instead
> D, [2016-03-30T15:48:02.508464 #5836] DEBUG -- : calling... on_xxx : on_notice
> D, [2016-03-30T15:48:02.508464 #5836] DEBUG -- : RECEIVE: PING :5FEBC0B3
> D, [2016-03-30T15:48:02.509467 #5836] DEBUG -- : calling... on_xxx : on_ping
> D, [2016-03-30T15:48:02.509467 #5836] DEBUG -- : SEND: PONG :
> D, [2016-03-30T15:48:02.616520 #5836] DEBUG -- : RECEIVE: :5FEBC0B3!nospoof@ircfire.linuxfire.com.cn PRIVMSG bcDICE :VERSION
> D, [2016-03-30T15:48:02.618524 #5836] DEBUG -- : calling... on_xxx : on_privmsg
> D, [2016-03-30T15:48:36.416696 #5836] DEBUG -- : RECEIVE: ERROR :Closing Link: bcDICE[_My ip address_](Ping timeout: 34 seconds)
> D, [2016-03-30T15:48:36.416696 #5836] DEBUG -- : calling... on_xxx : on_error

I am using your dicebot on a unrealircd IRC and it seems to be unable to join the channel,can you tell me how to solve the problem?
PS:This IRC uses UTF-8

**Comment by ysakasin** [comment]
Close this issue because it is a long time since created. If this problem still occurs, reopen it.
