### ISSUE TITLE
キルデスビジネス：難易度と補正値の区切り文字にカンマも使いたい

### ISSUE THREAD

**Issue by yuGit1985** [bcdice/BCDice#272]
キルデスビジネスのJDコマンドにおける難易度と補正値の区切りは+か-になっているが、
これだと負数が展開された時に符号が重なってしまう場合があるため、使いづらい場合がある

それらを踏まえ、現状のコマンドに加えて下記のものも使えるようにしたい
JD5,3,1
JD7,-1,3

**Comment by ysakasin** [comment]
提案ありがとうございます

提案いただいた形式だと、単に数値が羅列されるため、どの数値がどんな意味を持つのか一見わかりづらい気もします。
負数を展開した時の挙動を直せば十分だったりはしますでしょうか？

ファンブルの指定は最近のBCDiceでは `#[数字]` とするのが標準になりつつあるので、 `JD5#1` というような書き方ができるようにしようと思いますが、こちらについてはどうですか。

**Comment by yuGit1985** [comment]
コマンドから意味が分かりづらいのはその通りですね。
実装量、影響範囲も考えると、負数展開時の挙動を修正するのがベストかと思われます。

不勉強で申し訳ないのですが、#にするのが主流なのですね。
そうであれば合わせて実装すると直感的なコマンドになるので良いと思います。

**Comment by ysakasin** [comment]
了解です。
- 全部カンマで区切るのはやめて、負数が展開できるようにする
- ファンブル指定は `,[数字]`を残しつつ `#[数字]`でできるようにする
この二点を適用します。

現在BCDiceの次期バージョンに向けてプロジェクト全体で大幅な変更を行っていて、次回リリースは2021/01/01以降になる予定です。その点、ご了承ください。

**Comment by ysakasin** [comment]
`JD5+(1-2),4`のようなコマンドが動作するように修正しました。次回リリースをお待ちください。
