### ISSUE TITLE
エンドユーザーマニュアル

### ISSUE THREAD

**Issue by ysakasin** [bcdice/BCDice#274]
BCDiceがどどんとふから離れたことで、choiseなどの基本コマンドのヘルプメッセージがエンドユーザーに対して届かなくなっているため、エンドユーザーマニュアルを作る必要性が高い。

作るのは確定として、どの媒体を用いるかという問題がある。
思いつく限りの候補は以下。

- bcdice.org の小ページ
- [gitbook](https://www.gitbook.com/)
  - [ココフォリア公式Wiki](https://docs.ccfolia.com/) で使われている。Gitを使ったサービスだが、Wikiかと言われると微妙
- リポジトリの `/docs/` にMarkdownファイル直置き
- リポジトリのWiki
- 何かしらのWikiサービス

## 作ったドキュメントを読む人
エンドユーザー：ココフォリアやユドナリウムなど、オンセツール上でBCDiceのコマンドを使う人々

## ドキュメントをメンテナンスする人
BCDiceコミッタ：必須
有志：オプション

## 考えたいこと
どのサービスを使うのがいいか。各サービスの利点と欠点

**Comment by ysakasin** [comment]
bcdice.org にサブドメイン切って、 [honkit](https://github.com/honkit/honkit) 使うとか

**Comment by ysakasin** [comment]
良さげなサービスやツールがあったら、皆さんも追記お願いします

**Comment by R-F-D** [comment]
以下それぞれに該当する方の参加を
どの程度想定されていますか

1. システム対応コードの寄稿者
1. BCDice利用ツールには習熟しているが、いわゆる技術界隈に明るくないエンドユーザ

**Comment by ysakasin** [comment]
@R-F-D 

> システム対応コードの寄稿者
今回の登場人物には含まれません。
各ゲームシステムのヘルプメッセージはこのマニュアルには含めず、従来通りPlainテキストのヘルプメッセージをコード内に書き、各オンセツールがそれを表示します。

> BCDice利用ツールには習熟しているが、いわゆる技術界隈に明るくないエンドユーザ
「有志：オプション」に含まれます。彼らの参加は必須要件ではありません。
採用された手法がWiki系で、いろんな人が参加できる体勢なら協力してもらう、くらいの感覚です。

**Comment by ysakasin** [comment]
Honkitで書くことにしました。リポジトリは以下です。
https://github.com/bcdice/docs.bcdice.org

gitbook: 多人数編集は有料のため、プレビューを見れる人が限られてしまう。有志が参加しづらいので採用しなかった
bcdice.orgの子ページ: ページのデザインをするコストが高いので見送り
