### ISSUE TITLE
新クトゥルフのCCコマンドが先頭一致で振れる

### ISSUE THREAD

**Issue by blhsrwznrghfzpr** [bcdice/BCDice#298]
CCコマンドの直後に関係のない文字を（スペースを開けずに）記入してもロールできてしまう。

v3のREPLで確認。
```
[Cthulhu7th]> CCなにか
1D100 ＞ 63
[Cthulhu7th]> CC1<=50なにか
(1D100<=50) ボーナス・ペナルティダイス[1] ＞ 75, 35 ＞ 35 ＞ レギュラー成功
```

**Comment by ochaochaocha3** [comment]
コマンドの直後に関係ない文字を入れてもそのコマンドを実行できるかは、クトゥルフだけでなくゲームシステムごとに異なりますね。実害がないのでそのままに、というのが続いて今に至っていたはずです。挙動の統一は不可能ではありませんが相当な手間がかかるので、それに見合う長所があるかで判断するところかと思います。

**Comment by blhsrwznrghfzpr** [comment]
僕の考えですが、コマンドは書式が完全に一致しているものだけが実行される方がユーザーに親切だと思います。
（そして、ここ最近のメンテ方針がそうなっているように感じたのでissueに起票しています）

ある特定のコマンドが実行できるかはゲームシステムによって異なりますが、
複数のゲームシステムで記法の似通ったコマンドが存在するため、
ユーザーは一方のシステムで使用できたコマンドをもう一方でも使用できると勘違いする状況が発生しやすいと思います。

特にクトゥルフでは6版の`CCB`コマンドは新クトゥルフでは存在しませんが、
現状では先頭一致のため`CC`コマンドとして振れしまっています。
```
[Cthulhu7th]> CCB1
1D100 ＞ 16
[Cthulhu7th]> CCB<=50
1D100 ＞ 59
```
しかし上記の2つめの例では目標値を設定しているのに、コマンドが不正なためダイス結果のみとなっています。
結果としてユーザーの望む結果が得られない状況になります。

このような勘違いを抑制するには、そもそも不必要な文字の付いたコマンドを受け付けないようにして、
ユーザーにヘルプメッセージを見るように仕向けるようにしたほうがいいかと。
（現状で上記のような問い合わせが発生してないので、杞憂といえば杞憂ですし喫緊の問題でもないのは理解しています。）

**Comment by ysakasin** [comment]
yoshiさんが察してくださっていた方針でメンテしていました。

特定システムに限定した話だと、新クトゥルフ神話TRPGの`CC`コマンドでは意図的に目標値の四則演算による補正を認めないことにしています。しかしながら前方一致しかみていないため `cc<=10+30` は実行できてしまい、`CC<=10` として扱われます。

このように仕様と意図の違いから誤解が生まれることを避けるために、完全一致に寄せた方が良いだろうと考えています。Ochaさんのおっしゃる通り全てのコマンドに対して一括で直すのは到底無理なので、見つけ次第、完全一致に寄せていくという方針で良いのではないでしょうか。

コマンドに対する誤解やタイプミスで意図しないコマンドを実行してしまう例は、個人的な経験でも何度も目撃しました。

**Comment by ochaochaocha3** [comment]
> 見つけ次第、完全一致に寄せていくという方針で良いのではないでしょうか。
賛成します。

**Comment by ysakasin** [comment]
#330 で直しました
