### ISSUE TITLE
シノビガミ 行為判定のダイスにファンブル値の指定を追加したい

### ISSUE THREAD

**Issue by yuGit1985** [bcdice/BCDice#302]
ソースを読んだところ、2D6の合計が2以下であればファンブルとなっています
ところが、ご存じの通りシノビガミの戦闘中のファンブル値は可変です
キルデスビジネスはファンブル値の指定ができているので、シノビガミでもそのようなコマンドを追加して頂けないでしょうか？

今は大幅改変の時期と聞いています。
大変な時期かとは思いますが、もしよろしければご対応お願いいたします

**Comment by ysakasin** [comment]
@yuGit1985 提案ありがとうございます。`2D6`とは別に以下のようなコマンドを追加することになると思いますが、どうでしょうか

```
SG -> 2D6
SG@11 -> クリティカル値11
SG#3 -> ファンブル値3
SG@11#3 -> クリティカル値11、ファンブル値3
SG@11#3>=7
```

`@`や`#`による指定の省略時には従来のクリティカル/ファンブル値を採用します。

**Comment by yuGit1985** [comment]
他のシステムとの統一も取れていてよいと思います
v3の更新もあり大変かとは思いますが、お願いいたします。

**Comment by ysakasin** [comment]
ShinobiGamiにスペシャル値とファンブル値を指定できる行為判定コマンド`SG`を追加しました。次回リリースをお待ちください。
