### ISSUE TITLE
ダブルクロス 疾風怒涛式達成値ロールのC値と固定値の両方に四則演算を含めると不正な挙動

### ISSUE THREAD

**Issue by tonby** [bcdice/BCDice#318]
ダブルクロスの達成値ロールにて、C値を固定値の前に置く記法についてです。
固定値の四則演算は正しく機能します。例えば
10dx8+(5+5)
はC値8、固定値+10として認識されます。
また、C値の四則演算も正しく機能します。例えば
10dx(8-1)+5
はC値7、固定値+5として認識されます。
しかし、これらを同時に行おうとすると正しく機能しないようです。例えば
10dx(8-1)+(5+5)
はdx以降がすべてC値として認識され、C値17、固定値0として扱われるようです。
これはおそらく意図された動作ではないため、報告させて頂きます。
なお、CCFOLIAとSaipageの両方でこの動作を確認しました。
また、@の後にC値を記述する記法では正しく動作するようです。

**Comment by ysakasin** [comment]
```
➤ bundle exec ruby bin/repl.rb
BCDice REPL
>> "help" shows help messages.
[DiceBot]> use DoubleCross
[DoubleCross]> 10dx(8-1)+(5+5)
(10DX17) ＞ 9[1,2,2,3,5,7,7,8,8,9] ＞ 9
[DoubleCross]> 10dx(8-1)+10
(10DX7+10) ＞ 10[1,3,3,5,6,6,7,7,8,9]+10[7,8,9,10]+10[1,2,3,9]+1[1]+10 ＞ 41
```

**Comment by ysakasin** [comment]
@tonby 報告ありがとうございます。

この挙動ですが、DoubleCross固有の問題でなく、BCDiceが行っている前処理に問題があるようです。
修正しますので、次回リリースをお待ちください。
