### ISSUE TITLE
新クトゥルフ神話TRPGにおけるボーナスダイス／ペナルティダイスの上限下限を拡張したい

### ISSUE THREAD

**Issue by BrutalBEnforcer** [bcdice/BCDice#342]
一部の呪文や、選択ルールなどにより、ボーナスダイスやペナルティダイスが2を超える場合の処理を行いたい。

**Comment by ysakasin** [comment]
@BrutalBEnforcer 提案ありがとうございます！

ルールブックを確認したところ、日本語版ではボーナス・ペナルティダイスの個数の制約は書かれていませんが、これは翻訳時に抜け落ちたもののようで、英語版の記述によるとどちらも最大2個までのようです。

検討材料として、「一部呪文」の例を挙げていただけないでしょうか。
呪文名と掲載書籍、ページをお教えいただきたいです。

**Comment by BrutalBEnforcer** [comment]
早速の返信ありがとうございます。

> 検討材料として、「一部呪文」の例を挙げていただけないでしょうか。
例えば、次のようなものがあります。
・Bless(Folk) - The Grand Grimoire of Cthulhu Mythos Magic p.44
・Synchronicity - World War Cthulhu Cold War p.189

翻訳時の抜け漏れでございましたか、お騒がせしております。
邦訳版では、p.131左下のチェイス時の慎重な行動においては2が上限とあった記憶です。

**Comment by ysakasin** [comment]
@BrutalBEnforcer ありがとうございます。

それらの書籍が参照できないためお教えいただきたいのですが、
そちらの呪文にはボーナス・ペナルティダイスが2を超えることが明記されているのでしょうか？

**Comment by BrutalBEnforcer** [comment]
@ysakasin 確認ありがとうございます。

>呪文にはボーナス・ペナルティダイスが2を超えることが明記されているのでしょうか？
 
ボーナス・ペナルティダイスの上限については言及されておりません。

英語版を確認しておりますが、邦訳版にあったチェイス時の慎重な行動以外で、ボーナス・ペナルティダイス数の上限についての言及がまだ見つからずです……

**Comment by ysakasin** [comment]
ありがとうございます。

色々と検討しましたが、上限は緩和することにします。フルオートコマンドについては上限がルール上明示されているため、現状の仕様を維持します。

> ボーナス・ペナルティダイス数の上限についての言及

英語版を持っていないため又聞きで申し訳ありませんが、英語版p.91には以下のように書いてあるそうです。
（"a second (and so on)"ではなくa second のみ）
> a second bonus could be applied.

また、英語版キーパースクリーンには 2 max per roll と書かれているそうです。

**Comment by ysakasin** [comment]
@BrutalBEnforcer ボーナス・ペナルティダイス数の上限を100まで緩和しました。改めて提案ありがとうございます。次回リリースをお待ちください。

**Comment by ysakasin** [comment]
:memo: Discordでの議論部分 https://discord.com/channels/597133335243784192/598145833170501653/791889586216894484
