### ISSUE TITLE
フィルトウィズ：迷宮表追加要望、他

### ISSUE THREAD

**Issue by Rosatraums** [bcdice/BCDice#377]
先日は誤字修正および、伝説級の実装等の改修有難う御座いました。
大変遅くなってしまいましたが、フィルトウィズの追加迷宮表である「迷宮表／研究所」及び「迷宮表／砂漠」の追加要望、及び【デーモンカード】【白き神の束縛】のコマンド化提案についてまとめましたのでご確認お願いしたく書き込ませて頂きます。

***

- 【デーモンカード】効果表（コマンド：「DMC」あたり）
    - 【必殺技！】効果表（「HST」）とやりたい事は同じ
    - １Ｄ６を振って、そのダイス目によって発動するバフが違う【特技】
    - 他人にかかるバフであり、リロールが容易な為、【特技】に詳しくない他人が参照しやすいようにしたい

```
（出目：内容）

１：ジョーカー。２～５から好きな効果を選ぶ
２：スペード。〔命中〕に「SLv×5」のボーナスを与える
３：ハート。〔HP〕を「SLv×30」点回復
４：クラブ。あらゆる致傷力に「SLv×10」のボーナスを与える
５：ダイヤ。あらゆる防護点に「SLv×10」のボーナスを与える
６：デーモン。なんの効果も得られない
```

- 【白き神の束縛】効果表（コマンド案は界隈に聞いてみましたが特には出ませんでした）
    - 【必殺技！】効果表（「HST」）とやりたい事は同じ
    - １Ｄ６を振って、出目に対応するデバフを相手にかける【特技】
    - 行使者と、受け手が基本的に違う【特技】かつ、リロールが容易な為、参照しやすいようにしたい

```
１：力の束縛。次の使用者のターンまであらゆる攻撃の致傷力に-20のペナルティを与える
２：魔の束縛。次の使用者のターンまで【魔法】が使用できなくなる
３：腕の束縛。〔命中〕に-5のペナルティを与える
４：足の束縛。〔移動〕〔回避〕に-3のペナルティを与える
５：心の束縛。〔抵抗〕に-5のペナルティを与える
６：時の束縛。「使用：支援ターン」の【特技】が使用できなくなる
```

***

- 「迷宮表/研究所」、「迷宮表/砂漠」の作成
    - 難易度は「伝説級」非対応のため、『初級,中級,上級,悪夢』の４段階
    - ２－４以外の２－＊は他の迷宮表と同様の為、同じ書き方をする場合は伝説級の難易度部分を削除して書き写せるとは思います

    - 迷宮表/研究所（コマンド：LABD(E|N|H|L)([1-6])はどう？という提案はあった）
    - 迷宮表/砂漠（コマンド：SAND(E|N|H|L)([1-6])はどう？という提案はあった）
          - ！？は半角にするべきか？
          - あわせて作るべき「研究所エンカウント表」「砂漠エンカウント表」のコマンドについては提案はありませんでした。

「迷宮表/研究所」、「迷宮表/砂漠」の出目と対応する内容のまとめ、および「研究所エンカウント表」「砂漠エンカウント表」の一覧をTXTで纏めましたので添付させて頂きます。
……が、添付マズかったらいっていただければと思います。GitHubはじめてですので……

[４フィルトウィズ迷宮表追加、他.txt](https://github.com/bcdice/BCDice/files/5899239/default.txt)

長くなってしまい申し訳御座いませんが、よろしくお願いいたします。

**Comment by ysakasin** [comment]
@Rosatraums 
> 「迷宮表/研究所」、「迷宮表/砂漠」の作成

元となるであろう `RAND` コマンドの仕様が複雑すぎることと、いただいたデータと解離しているため、どのような実装が求められているのか全くわかりませんでした。

コマンドの入力がどんな意味で、どのようなダイスロールが発生し、それらの結果からどのように表を参照するのか詳しく教えてください。また、 `2-4` と言われても元々の引数が多いため何を意味するのかわかりません。D66で24のときを意味するのでしょうか？

**Comment by Rosatraums** [comment]
・RANDコマンドについて
ラウンドの１番最初にそのラウンドで使用する
「地形」「イベント概要」「イベント詳細」 を決定します。
地形、イベント概要、イベント詳細の順番に１Ｄを振ってその結果を参照してください。
「イベント詳細」でなんらかの判定を求められた際は、
原則としてそのラウンドの行動を処理する前に判定を行ってください。
ただし、１ラウンド目の「イベント概要」は必ず「４：エンカウント」になります。

という、「夢幻の迷宮」のイベント表の決定を行っているものになります。
追加要望として出したものは、「追加地形」といえるもので、追加地形を指定して振る場合に使用されることを想定しているので
「地形」を決定する１つ目の１Ｄ６が省略されて『「イベント概要」-「イベント詳細」』のD66Nになるかと思います。
"１ラウンド目の「イベント概要」は必ず「４：エンカウント」になります。"という仕組みがあるので、
可能なら「イベント概要」の１つ目のダイスを固定できるようにできたら便利ではあると思います。

イベントの内容として判定を要求してくる部分などが挑む「夢幻の迷宮」の難易度によって変化するので
それで元となるRANDコマンドではその部分で[difficulty]が使われていました。
（投げたデータでは『1000, 2000, 5000, 10000』など『』で囲ってある部分が難易度で変化する部分になります。
　どういうコマンドで実装されるかわからなかったので取り合えずコマンドとかで使いそうな記号を避けたものでしたが
　説明を忘れておりました。申し訳ございません……！）

・D66で24のときを意味するのでしょうか？
なのでこの挙動で問題ないと思います。
D66Nで25が出たらミミックの罠の内容が返ってくるかたちになると嬉しいです。
