### ISSUE TITLE
四則演算：除算の結果が負となった場合の端数処理が正しくない

### ISSUE THREAD

**Issue by ochaochaocha3** [bcdice/BCDice#58]
計算コマンド `C(...)` において、除算 `/` の結果が負となった場合の端数処理に問題があります。

# 環境

BCDice v2.02.80

* [どどんとふTRPG.NET第1サーバ](https://d.trpg.net/)（どどんとふv1.49.04.01）において確認しました。

# 症状

除算 `/` の結果が負となった場合、絶対値が大きくなる方向に結果が丸められます。BCDiceでは、演算子 `/` は端数を切り捨てる除算であるため、絶対値が小さくなる方向に結果が丸められなければならないはずです。なお、結果が正となった場合は問題ありません。

以下の図に、問題の発生例を示します。

<img width="168" alt="bcdice_bug_div_rounding" src="https://user-images.githubusercontent.com/2551173/61195631-3147af00-a704-11e9-9719-4a57cbe4a888.png">

図：どどんとふv1.49.04.01（BCDice v2.02.80が動作）における除算の実行結果

**Comment by ysakasin** [comment]
実数における一般的な切り上げ、切り捨て、四捨五入の要件を十分に満たしていると思いますが見当違いでしょうか？

- 切り捨て（floor）：より小さい値に丸められる
- 切り上げ（ceil）：より大きい値に丸められる
- 四捨五入（round）：近い整数に丸められる

```
$ irb
irb(main):001:0> 12.0/5
=> 2.4
irb(main):002:0> -2.4.floor
=> -3
irb(main):003:0> -2.4.ceil
=> -2
irb(main):004:0> -2.4.round
=> -2
irb(main):005:0> 2.4.floor
=> 2
```

**Comment by ochaochaocha3** [comment]
もともと `C(1+2-3*4/5)` が期待される結果となっていないことから発覚したのですが、どう直していくところでしょうか？

期待される結果：

```
1 + 2 - 3 * 4 / 5 = (1 + 2) - ((3 * 4) / 5) = 3 - (12 / 5) = 3 - 2 = 1
```

現在の挙動（推測）：

```
1 + 2 - 3 * 4 / 5 = 3 - 3 * 4 / 5 = 3 + (-3) * 4 / 5 = 3 + (-12) / 5 = 3 + (-2.4)
-> 3 + (-3) = 0
```

**Comment by ysakasin** [comment]
現在の挙動は、Rubyと同様に切り捨てをfloor、切り上げをceilと定義した場合と整合が取れているため問題ないと思っています。切り捨てと切り上げの定義を変更する必要があるのでしたら、理由を添えて提案をお願いします。

計算順序の方はまだ追いきれてないので、確認します。

**Comment by ochaochaocha3** [comment]
Rubyの動作をこちらでも確認してみました。

```
[1] pry(main)> # 整数同士の除算
[2] pry(main)> 12/5
=> 2
[3] pry(main)> (-12)/(-5)
=> 2
[4] pry(main)> -12/5
=> -3
[5] pry(main)> 12/(-5)
=> -3
[6] pry(main)> # 多項式の項の順番の変更
[7] pry(main)> 1+2-3*4/5
=> 1
# (1 + 2) - ((3 * 4) / 5) = 3 - 12 / 5 = 3 - 2 = 1
[8] pry(main)> -3*4/5+1+2
=> 0
# ((-3 * 4) / 5) + (1 + 2) = (-12 / 5) + 3 = -3 + 3 = 0
```

分かったことは、

* 現在の切り捨ておよび切り上げはそれぞれfloor、ceilで問題ない（Rubyと同じ挙動）
* 多項式の評価の仕方が異なる。どどんとふでは減算を負数の加算に変換しているため、多項式の評価結果が直感的でないものになる。

ということでした。結論として、 #61「計算処理の演算順序が不正」で対応するのが良さそうだと判断しました。
