### ISSUE TITLE
複数ダイスを振って大きいもの/小さいものから任意個を取る処理がしたい

### ISSUE THREAD

**Issue by NanasuNANA** [bcdice/BCDice#88]
#87 とも関連するが、複数ダイスを振って大きいもの/小さいものから任意個を取るケースは多そう（MAGIUS、フォーリナー、D&D5th、etc）なので、個々のゲーム用に実装よりも標準にあるとよいのではないか。

ダイスコードの提案としてはnDx記法に、(K|D)(H|L)\d+を追記した場合、結果のダイスから大きいもの/小さいものを任意個を取るまたは除く（Keep Highest、Keep Lowest、Drop Highest、Drop Lowest）。

例）
* 3d6KH2+3
MAGIUSの技能あり判定、3つのD6から大きいもの二つを取り合計し、能力値を足す。

* 4d6DL1
D&D3版以降の能力値決定ダイス、4つのD6を振り、最小1個を取り除く。

* 2d20KL1+1d4+4 
2つのD20の小さい方から1つ取り、1d4+4を足す。D&Dthの不利の判定にブレスがかかり、ボーナスが+4の場合。

**Comment by ochaochaocha3** [comment]
Discord（#よろず相談）より、テストデータ形式の具体例：

```
input:
2D20KH1+1
output:
DiceBot : (2D20KH1+1) ＞ 20[1,20]+1 ＞ 21
rand:1/20,20/20
============================
input:
4D6DL1
output:
DiceBot : (4D6DL1) ＞ 14[5,2,3,6] ＞ 14
rand:5/6,2/6,3/6,6/6
============================
```

**Comment by R-F-D** [comment]
マギウスの技能あり判定についてですが「3個振って任意の2個を採用する」が正しいですね。

多くの場合は「大きい方から2個」で問題ないですが
小さい方を選ぶという選択肢もありえます。

攻撃のときにダメージの手加減をするですとか、
確かスレイヤーズ系では達成値が高すぎると駄目というギミックがあったはずです。
