### ISSUE TITLE
ディレクトリ構成修正

### ISSUE THREAD

**Issue by ysakasin** [bcdice/BCDice#94]
Ver3.0でRubyっぽいディレクトリ構成に直す。提案歓迎

**Comment by ochaochaocha3** [comment]
Rubyのgemの標準的な配置に倣うと、まず `lib/ルートモジュール/` 以下にファイルを置くことになりそうです。

そこで、最初にルートモジュールの名前を決めることが課題になります。素直に考えれば `BCDice` ですが、主要なクラスの `BCDice` と被って少し分かりにくい（`BCDice::BCDice` のようになる）かもしれません。[言語処理系生成ツールANTLRのgem](https://github.com/ohboyohboyohboy/antlr3)のように、バージョンも含めた `BCDice3` とするのはひとつの案ですが、同様の例はほとんどないようです。

**Comment by ochaochaocha3** [comment]
関連：ダイスボットのインターフェース案（酒田　シンジさん考案）
https://gist.github.com/ysakasin/1464a15828f4beeb2988b61f924bacb9

**Comment by ysakasin** [comment]
```
BCDice
├── lib/
│   ├── bcdice/
│   │   ├── common_command/
│   │   │   ├── add_dice.rb
│   │   │   └── choice.rb
│   │   ├── dice_table/
│   │   │   ├── d66_table.rb
│   │   │   └── table.rb
│   │   ├── extra_table.rb
│   │   ├── system/
│   │   ├── system_base.rb
│   │   └── version.rb
│   └── bcdice.rb
└── test/
    └── data/
```
